services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: phys-sir-env
    working_dir: /app
    volumes:
      - .:/app:rw
      - ./mlflow:/app/mlflow
    environment:
      - HOME=/home/appuser
      - XDG_CACHE_HOME=/home/appuser/.cache
      - XDG_CONFIG_HOME=/home/appuser/.config
      - MLFLOW_TRACKING_URI=sqlite:///mlflow/mlflow.db
      - USER=appuser
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    command: >
      bash -c "
        mkdir -p /app/mlflow/artifacts &&
        touch /app/mlflow/mlflow.db &&
        mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /app/mlflow/artifacts --host 0.0.0.0 --port 5000 &
        sleep 2 &&
        bash
      "
    user: "1000:1000"
    ports:
      - "8888:8888"
      - "5000:5000"
