defaults:
  - compartmental: sir
  - network: test
  - training: test
  - observables: synthetic
  - _self_

numerical_ode_params:
  t_span: [0, 50]
  t_eval_points: 1000
  solve_ode: true

plotting:
  title: "Compartmental Model Simulation"

data:
  save_data: true
